name: Continuous Integration
on: [pull_request]

jobs:
  Validate:
    name: 'Validate Pull Request'
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '12.x'
    steps:
      - name: 'Git checkout'
        uses: actions/checkout@v3.1.0

      # Beginning of yarn setup, keep in sync between all workflows
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'Use cached node_modules'
        id: cache-modules
        uses: actions/cache@v2.1.4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-v${{ matrix.node-version }}-node_modules-${{ hashFiles('yarn.lock', '**/package.json') }}
      - name: 'Find location of global yarn cache'
        id: yarn-cache
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: 'Cache global yarn cache'
        uses: actions/cache@v2.1.4
        if: steps.cache-modules.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: 'Install dependency'
        run: yarn install --frozen-lockfile
        # End of yarn setup

      - name: 'Audit dependencies'
        run: /bin/sh -c 'yarn audit --level high; [[ $? -ge 8 ]] && exit 1 || exit 0'
      - name: 'Types check'
        run: yarn type-check
      - name: 'Prettier'
        run: yarn format:check
      - name: 'ESLint'
        run: yarn lint
      - name: 'Build'
        run: yarn build
